name: onecx-theme
home: ""
sources: []
version: 0.0.0
description: ""
keywords: []
maintainers: []
icon: ""
apiversion: v2
condition: ""
tags: ""
appversion: 0.0.0
deprecated: false
annotations: {}
kubeversion: ""
dependencies:
- name: onecx-theme-svc
  version: 0.0.0-rc.12
  repository: ""
  condition: ""
  tags: []
  enabled: false
  importvalues: []
  alias: ""
type: ""
